# .github/workflows/main.yml
# This workflow automates building, testing, and deploying the Tic Tac Toe game for branch merges.
name: Tic Tac Toe CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: "Debug: List workspace contents"
        run: ls -R $GITHUB_WORKSPACE

      - name: Setup Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.6.3
          aqtversion: ">=3.1,<3.2" 
          host: linux
          target: desktop
          arch: gcc_64

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libsqlite3-dev libssl-dev

      - name: Run qmake
        working-directory: .
        run: qmake TicTacToe1.pro

      - name: Build project
        working-directory: .
        run: make -j$(nproc)

      - name: Build Qt Tests
        working-directory: .
        run: |
          qmake TicTacToe1.pro CONFIG+=test
          make -j$(nproc)

      - name: Run tests
        working-directory: ./tests
        run: ./test_game

      - name: Package executable
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: .
        run: tar -czvf tic-tac-toe.tar.gz TicTacToe1

      - name: Upload artifacts
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: TicTacToe-Linux-Build
          path: tic-tac-toe.tar.gz
