# .github/workflows/main.yml
# This workflow automates building, testing, and deploying the Tic Tac Toe game for branch merges.
name: Tic Tac Toe CI/CD

# Controls when the workflow will run
on:
  # Trigger on push or pull request to the 'main' branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual runs from the Actions tab
  workflow_dispatch:

# Jobs in the workflow
jobs:
  build:
    # Run on Ubuntu for Qt and C++ compatibility
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # Step 2: Debug workspace contents
      - name: Debug: List workspace contents
        run: ls -R $GITHUB_WORKSPACE

      # Step 3: Set up Qt 6.6.3
      - name: Setup Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.3'
          aqtversion: '==3.1.*'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'

      # Step 4: Install build dependencies
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libsqlite3-dev libssl-dev

      # Step 5: Configure main project with qmake
      - name: Run qmake
        working-directory: .
        run: qmake TicTacToe1.pro

      # Step 6: Build main project
      - name: Build project
        working-directory: .
        run: make -j$(nproc)

      # Step 7: Configure and build Qt Test
      - name: Build Qt Tests
        working-directory: .
        run: |
          qmake TicTacToe1.pro "CONFIG+=test"
          make -j$(nproc)

      # Step 8: Run Qt Tests
      - name: Run tests
        working-directory: ./tests
        run: ./test_game_logic

      # Step 9: Package executable for CD
      - name: Package executable
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: .
        run: tar -czvf tic-tac-toe.tar.gz TicTacToe1

      # Step 10: Upload artifact for CD
      - name: Upload artifacts
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: TicTacToe-Linux-Build
          path: tic-tac-toe.tar.gz
```
